### ISSUE TITLE
Upgrade the build process to work with recent versions of the Android SDK.

### ISSUE THREAD

**Issue by chr15m** [chr15m/PdDroidParty#26]

**Comment by tkirshboim** [comment]
Hi @chr15m , I though I'd ping you here in case you didn't see my pull request that fixes this issue:
https://github.com/chr15m/PdDroidParty/pull/28

**Comment by chr15m** [comment]
@tkirshboim excellent, thanks so much!

PdDroidParty really needs a new maintainer as it doesn't get the attention it deserves from me.

**Comment by tkirshboim** [comment]
@chr15m you're welcome :blush:
I'm not using the app so often that I think I could maintain it long term, but I'll create PRs if I manage to fix or improve something.
Maybe I'll find some time to fix #25 since I also had to work around it recently when I wanted to try out SyncJams with your acid patch (which worked really nicely btw :top: ).
