### ISSUE TITLE
Get USB Midi permission at install time

### ISSUE THREAD

**Issue by chr15m** [chr15m/PdDroidParty#39]
@tkirshboim do you know if there is a way to do this so the user isn't prompted every time they connect a MIDI device?

**Comment by tkirshboim** [comment]
@chr15m How do you test this? How do you generate the permission request?
I guess I need a USB midi device for that?
Could you share a screenshot of the permission request?

**Comment by chr15m** [comment]
Hi @tkirshboim yep you plug a USB midi device in using an OTG USB cable and then select "midi" from the PdDroidParty menu:

MIDI menu option:

![screenshot_2018-07-05-16-34-25](https://user-images.githubusercontent.com/67130/42313345-1bc9e53c-8075-11e8-97b0-6256676c580d.png)

![screenshot_2018-07-05-16-34-33](https://user-images.githubusercontent.com/67130/42313388-35a01ff8-8075-11e8-8af4-d59da19125dc.png)

This one pops up every time, even if you select "Use by default...":

![screenshot_2018-07-05-16-34-41](https://user-images.githubusercontent.com/67130/42313395-3a9fd840-8075-11e8-81be-761d5ae0e4d5.png)

Then you have to select the input device to give permission for:

![screenshot_2018-07-05-16-35-07](https://user-images.githubusercontent.com/67130/42313424-4e1147ce-8075-11e8-97f7-d3e174b9489d.png)

And then the output device to give permission for:

![screenshot_2018-07-05-16-35-13](https://user-images.githubusercontent.com/67130/42313436-567d485e-8075-11e8-9a85-053c39b13cd2.png)

So four steps are required to use a USB MIDI device.

Here's the relevant code:

https://github.com/chr15m/PdDroidParty/blob/master/src/cx/mccormick/pddroidparty/PdDroidParty.java#L309-L382

Hm actually looking at this there may be a way to do it without quite so many prompts. Presumably if the user has plugged the device in they want to use all of its capabilities. Maybe @nettoyeurny or @joebowbeer have an idea about this.

**Comment by tkirshboim** [comment]
@chr15m I don't have a USB MIDI device to test this with at the moment. I could give it a try when I manage to get one.

One hint I could give about this topic, is that there is a newer MIDI API for Android since Android 6.0. As far as I understand this API is not used by PdDroidParty (or by the pd-for-android samples for that matter):
https://developer.android.com/reference/android/media/midi/package-summary

Note that the API is only available from API level 23 and PdDroidParty currently has a minSdkVersion of 17.. So using the new API won't work for versions below 23.

**Comment by joebowbeer** [comment]
Also see:

https://github.com/philburk/android-midisuite

I think the author is working for Google now.
