### ISSUE TITLE
reduce accepted filetypes

### ISSUE THREAD

**Issue by umlaeute** [chr15m/PdDroidParty#52]
As of lately, I haven't used PdDroidParty much, but there's an issue I find so annoying that I actually uninstalled it:

*Once it is installed, it registers for *all* files.*

Whenever I try to open a PDF, my phone asks if I want to open it with `PdDroidParty`.
Whenever I try to open a `.org`-file, my phone asks if I want to open it with `PdDroidParty`.
Whenever I try to open a `.gpx`-file, my phone asks if I want to open it with `PdDroidParty`.
...

Of course, PdDroidParty has no clue what to do with these files, so it will just crash with an error:
> File Format not Supported, or bad file

this is on "Fairphone Open 19.11.2", which is based on "Android-7.1.2".

PS: PdDroidParty is not alone; there's other applications  that behave similar; but PdDroidParty is the app where I care most ;-)

**Comment by chr15m** [comment]
Mother of god that's awful. Will fix.

**Comment by chr15m** [comment]
Can fix #45 at the same time.

**Comment by chr15m** [comment]
The good news is I have stopped PdDroidParty from asking to open absolutely every file. The bad news is it now often misses legitimate `.pdz` files. The reasons for this are complex but basically come down to Android security. Apps often pass files around as anonymous `content://...` blobs with no file extension, and because the `.pdz` extension has no well known mime-type it gets a mime-type of `application/octet-stream`. So I will commit a fix that allows opening of `.pdz` files downloaded in the browser but nowhere else (e.g. sending them by email won't work).

**Comment by chr15m** [comment]
@umlaeute I have pushed a new build. Please re-open this issue if the problem persists.
