### ISSUE TITLE
SVG theming compatibility broken ?

### ISSUE THREAD

**Issue by b2renger** [chr15m/PdDroidParty#9]
I tried to use my old droidparty projects and it seems that something in svg theming. When I loaded the patches unchanged the gui was not dislaying, but when I removed all svg files from the folder the gui appeared and the patch worked again.

I haven't dug further, needs to be confirmed

**Comment by mgsx-dev** [comment]
I've found and solved the problem, since android 4.2, views are hardware accelerated and SVG don't render anymore (it seems some canvas draw methods not allowed in hardware accelerated mode). This bug is discussed in SVG Android libray bug tracker : https://github.com/pents90/svg-android/issues/7 and a solution is discussed here : http://stackoverflow.com/questions/13987288/svg-image-not-visible-in-android-3-0-with-same-code/13992014#13992014

The solution i've implemented is to disable hardware accelerated in the patch view (3 or 4 lines of code), I'll send you a pull request today.

**Comment by mgsx-dev** [comment]
pull request created https://github.com/chr15m/PdDroidParty/pull/24
enjoy.
